/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GisYieldRouteImport } from './routes/gis.yield'
import { Route as GisTerrainRouteImport } from './routes/gis.terrain'
import { Route as GisNdviRouteImport } from './routes/gis.ndvi'
import { Route as GisNdreRouteImport } from './routes/gis.ndre'
import { Route as GisMapRouteImport } from './routes/gis.map'
import { Route as GisHealthRouteImport } from './routes/gis.health'
import { Route as FarmYieldRouteImport } from './routes/farm.yield'
import { Route as FarmPlantsRouteImport } from './routes/farm.plants'
import { Route as FarmOverviewRouteImport } from './routes/farm.overview'
import { Route as FarmHistoryRouteImport } from './routes/farm.history'
import { Route as FarmHealthRouteImport } from './routes/farm.health'
import { Route as FarmGrowthRouteImport } from './routes/farm.growth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GisYieldRoute = GisYieldRouteImport.update({
  id: '/gis/yield',
  path: '/gis/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const GisTerrainRoute = GisTerrainRouteImport.update({
  id: '/gis/terrain',
  path: '/gis/terrain',
  getParentRoute: () => rootRouteImport,
} as any)
const GisNdviRoute = GisNdviRouteImport.update({
  id: '/gis/ndvi',
  path: '/gis/ndvi',
  getParentRoute: () => rootRouteImport,
} as any)
const GisNdreRoute = GisNdreRouteImport.update({
  id: '/gis/ndre',
  path: '/gis/ndre',
  getParentRoute: () => rootRouteImport,
} as any)
const GisMapRoute = GisMapRouteImport.update({
  id: '/gis/map',
  path: '/gis/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GisHealthRoute = GisHealthRouteImport.update({
  id: '/gis/health',
  path: '/gis/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmYieldRoute = FarmYieldRouteImport.update({
  id: '/farm/yield',
  path: '/farm/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmPlantsRoute = FarmPlantsRouteImport.update({
  id: '/farm/plants',
  path: '/farm/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmOverviewRoute = FarmOverviewRouteImport.update({
  id: '/farm/overview',
  path: '/farm/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmHistoryRoute = FarmHistoryRouteImport.update({
  id: '/farm/history',
  path: '/farm/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmHealthRoute = FarmHealthRouteImport.update({
  id: '/farm/health',
  path: '/farm/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmGrowthRoute = FarmGrowthRouteImport.update({
  id: '/farm/growth',
  path: '/farm/growth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farm/growth': typeof FarmGrowthRoute
  '/farm/health': typeof FarmHealthRoute
  '/farm/history': typeof FarmHistoryRoute
  '/farm/overview': typeof FarmOverviewRoute
  '/farm/plants': typeof FarmPlantsRoute
  '/farm/yield': typeof FarmYieldRoute
  '/gis/health': typeof GisHealthRoute
  '/gis/map': typeof GisMapRoute
  '/gis/ndre': typeof GisNdreRoute
  '/gis/ndvi': typeof GisNdviRoute
  '/gis/terrain': typeof GisTerrainRoute
  '/gis/yield': typeof GisYieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farm/growth': typeof FarmGrowthRoute
  '/farm/health': typeof FarmHealthRoute
  '/farm/history': typeof FarmHistoryRoute
  '/farm/overview': typeof FarmOverviewRoute
  '/farm/plants': typeof FarmPlantsRoute
  '/farm/yield': typeof FarmYieldRoute
  '/gis/health': typeof GisHealthRoute
  '/gis/map': typeof GisMapRoute
  '/gis/ndre': typeof GisNdreRoute
  '/gis/ndvi': typeof GisNdviRoute
  '/gis/terrain': typeof GisTerrainRoute
  '/gis/yield': typeof GisYieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farm/growth': typeof FarmGrowthRoute
  '/farm/health': typeof FarmHealthRoute
  '/farm/history': typeof FarmHistoryRoute
  '/farm/overview': typeof FarmOverviewRoute
  '/farm/plants': typeof FarmPlantsRoute
  '/farm/yield': typeof FarmYieldRoute
  '/gis/health': typeof GisHealthRoute
  '/gis/map': typeof GisMapRoute
  '/gis/ndre': typeof GisNdreRoute
  '/gis/ndvi': typeof GisNdviRoute
  '/gis/terrain': typeof GisTerrainRoute
  '/gis/yield': typeof GisYieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farm/growth'
    | '/farm/health'
    | '/farm/history'
    | '/farm/overview'
    | '/farm/plants'
    | '/farm/yield'
    | '/gis/health'
    | '/gis/map'
    | '/gis/ndre'
    | '/gis/ndvi'
    | '/gis/terrain'
    | '/gis/yield'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/farm/growth'
    | '/farm/health'
    | '/farm/history'
    | '/farm/overview'
    | '/farm/plants'
    | '/farm/yield'
    | '/gis/health'
    | '/gis/map'
    | '/gis/ndre'
    | '/gis/ndvi'
    | '/gis/terrain'
    | '/gis/yield'
  id:
    | '__root__'
    | '/'
    | '/farm/growth'
    | '/farm/health'
    | '/farm/history'
    | '/farm/overview'
    | '/farm/plants'
    | '/farm/yield'
    | '/gis/health'
    | '/gis/map'
    | '/gis/ndre'
    | '/gis/ndvi'
    | '/gis/terrain'
    | '/gis/yield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmGrowthRoute: typeof FarmGrowthRoute
  FarmHealthRoute: typeof FarmHealthRoute
  FarmHistoryRoute: typeof FarmHistoryRoute
  FarmOverviewRoute: typeof FarmOverviewRoute
  FarmPlantsRoute: typeof FarmPlantsRoute
  FarmYieldRoute: typeof FarmYieldRoute
  GisHealthRoute: typeof GisHealthRoute
  GisMapRoute: typeof GisMapRoute
  GisNdreRoute: typeof GisNdreRoute
  GisNdviRoute: typeof GisNdviRoute
  GisTerrainRoute: typeof GisTerrainRoute
  GisYieldRoute: typeof GisYieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis/yield': {
      id: '/gis/yield'
      path: '/gis/yield'
      fullPath: '/gis/yield'
      preLoaderRoute: typeof GisYieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis/terrain': {
      id: '/gis/terrain'
      path: '/gis/terrain'
      fullPath: '/gis/terrain'
      preLoaderRoute: typeof GisTerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis/ndvi': {
      id: '/gis/ndvi'
      path: '/gis/ndvi'
      fullPath: '/gis/ndvi'
      preLoaderRoute: typeof GisNdviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis/ndre': {
      id: '/gis/ndre'
      path: '/gis/ndre'
      fullPath: '/gis/ndre'
      preLoaderRoute: typeof GisNdreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis/map': {
      id: '/gis/map'
      path: '/gis/map'
      fullPath: '/gis/map'
      preLoaderRoute: typeof GisMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis/health': {
      id: '/gis/health'
      path: '/gis/health'
      fullPath: '/gis/health'
      preLoaderRoute: typeof GisHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm/yield': {
      id: '/farm/yield'
      path: '/farm/yield'
      fullPath: '/farm/yield'
      preLoaderRoute: typeof FarmYieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm/plants': {
      id: '/farm/plants'
      path: '/farm/plants'
      fullPath: '/farm/plants'
      preLoaderRoute: typeof FarmPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm/overview': {
      id: '/farm/overview'
      path: '/farm/overview'
      fullPath: '/farm/overview'
      preLoaderRoute: typeof FarmOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm/history': {
      id: '/farm/history'
      path: '/farm/history'
      fullPath: '/farm/history'
      preLoaderRoute: typeof FarmHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm/health': {
      id: '/farm/health'
      path: '/farm/health'
      fullPath: '/farm/health'
      preLoaderRoute: typeof FarmHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm/growth': {
      id: '/farm/growth'
      path: '/farm/growth'
      fullPath: '/farm/growth'
      preLoaderRoute: typeof FarmGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmGrowthRoute: FarmGrowthRoute,
  FarmHealthRoute: FarmHealthRoute,
  FarmHistoryRoute: FarmHistoryRoute,
  FarmOverviewRoute: FarmOverviewRoute,
  FarmPlantsRoute: FarmPlantsRoute,
  FarmYieldRoute: FarmYieldRoute,
  GisHealthRoute: GisHealthRoute,
  GisMapRoute: GisMapRoute,
  GisNdreRoute: GisNdreRoute,
  GisNdviRoute: GisNdviRoute,
  GisTerrainRoute: GisTerrainRoute,
  GisYieldRoute: GisYieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
